# Data about the CASD-NMR entries
#from cing.NRG.CasdNmrMassageCcpnProject import programHoH
programHoH = {
 'AR3436A': {'Cheshire': 'XPLOR',
             'Frankfurt': 'CYANA',
             'Lyon': None,
             'Lyon2': None,
             'Lyon3': 'CYANA',
             'Paris': None,
             'Paris2': None,
             'Piscataway': None,
             'Piscataway2': 'XPLOR',
             'Seattle': None,
             'Seattle2': 'PDB',
             'Seattle3': None,
             'Seattle4': None,
             'Seattle5': None,
             'Utrecht': None,
             'Utrecht2': 'XPLOR'},
 'AtT13': {'Cheshire': None,
           'Frankfurt': 'CYANA',
           'Lyon': None,
           'Lyon2': None,
           'Lyon3': 'CYANA',
           'Paris': 'XPLOR',
           'Paris2': None,
           'Piscataway': 'XPLOR',
           'Piscataway2': None,
           'Seattle': None,
           'Seattle2': None,
           'Seattle3': 'PDB',
           'Seattle4': 'PDB',
           'Seattle5': None,
           'Utrecht': 'XPLOR',
           'Utrecht2': None},
 'CGR26A': {'Cheshire': 'CYANA',
            'Frankfurt': 'CYANA',
            'Lyon': 'CYANA',
            'Lyon2': None,
            'Lyon3': None,
            'Paris': 'XPLOR',
            'Paris2': None,
            'Piscataway': 'XPLOR',
            'Piscataway2': None,
            'Seattle': None,
            'Seattle2': None,
            'Seattle3': None,
            'Seattle4': 'PDB',
            'Seattle5': 'PDB',
            'Utrecht': None,
            'Utrecht2': 'XPLOR'},
 'CtR69A': {'Cheshire': 'CYANA',
            'Frankfurt': 'CYANA',
            'Lyon': 'CYANA',
            'Lyon2': 'CYANA',
            'Lyon3': None,
            'Paris': 'XPLOR',
            'Paris2': None,
            'Piscataway': 'XPLOR',
            'Piscataway2': None,
            'Seattle': None,
            'Seattle2': None,
            'Seattle3': None,
            'Seattle4': 'PDB',
            'Seattle5': None,
            'Utrecht': 'XPLOR',
            'Utrecht2': None},
 'ET109Aox': {'Cheshire': None,
              'Frankfurt': 'CYANA',
              'Lyon': 'CYANA',
              'Lyon2': None,
              'Lyon3': None,
              'Paris': 'XPLOR',
              'Paris2': None,
              'Piscataway': None,
              'Piscataway2': 'XPLOR',
              'Seattle': 'PDB',
              'Seattle2': None,
              'Seattle3': None,
              'Seattle4': None,
              'Seattle5': None,
              'Utrecht': None,
              'Utrecht2': 'XPLOR'},
 'ET109Ared': {'Cheshire': 'CYANA',
               'Frankfurt': 'CYANA',
               'Lyon': 'CYANA',
               'Lyon2': None,
               'Lyon3': None,
               'Paris': 'XPLOR',
               'Paris2': None,
               'Piscataway': None,
               'Piscataway2': 'XPLOR',
               'Seattle': 'PDB',
               'Seattle2': None,
               'Seattle3': None,
               'Seattle4': None,
               'Seattle5': None,
               'Utrecht': None,
               'Utrecht2': 'XPLOR'},
 'HR5537A': {'Cheshire': 'CYANA',
             'Frankfurt': 'CYANA',
             'Lyon': None,
             'Lyon2': None,
             'Lyon3': 'CYANA',
             'Paris': 'XPLOR',
             'Paris2': None,
             'Piscataway': None,
             'Piscataway2': 'XPLOR',
             'Seattle': None,
             'Seattle2': None,
             'Seattle3': 'PDB',
             'Seattle4': None,
             'Seattle5': None,
             'Utrecht': None,
             'Utrecht2': 'XPLOR'},
 'NeR103A': {'Cheshire': 'CYANA',
             'Frankfurt': 'CYANA',
             'Lyon': 'CYANA',
             'Lyon2': 'CYANA',
             'Lyon3': None,
             'Paris': 'XPLOR',
             'Paris2': None,
             'Piscataway': 'XPLOR',
             'Piscataway2': None,
             'Seattle': None,
             'Seattle2': None,
             'Seattle3': None,
             'Seattle4': 'PDB',
             'Seattle5': None,
             'Utrecht': None,
             'Utrecht2': 'XPLOR'},
 'PGR122A': {'Cheshire': 'CYANA',
             'Frankfurt': 'CYANA',
             'Lyon': 'CYANA',
             'Lyon2': None,
             'Lyon3': None,
             'Paris': None,
             'Paris2': 'XPLOR',
             'Piscataway': 'XPLOR',
             'Piscataway2': None,
             'Seattle': None,
             'Seattle2': None,
             'Seattle3': None,
             'Seattle4': 'PDB',
             'Seattle5': None,
             'Utrecht': 'XPLOR',
             'Utrecht2': None},
 'VpR247': {'Cheshire': 'CYANA',
            'Frankfurt': 'CYANA',
            'Lyon': None,
            'Lyon2': None,
            'Lyon3': 'CYANA',
            'Paris': 'XPLOR',
            'Paris2': None,
            'Piscataway': None,
            'Piscataway2': 'XPLOR',
            'Seattle': None,
            'Seattle2': 'PDB',
            'Seattle3': None,
            'Seattle4': None,
            'Seattle5': None,
            'Utrecht': None,
            'Utrecht2': 'XPLOR'},
 '1brv': {  'A': 'CYANA',
            'B': 'CYANA',
            'C': 'CYANA',
            }
}