ARCHIVE_NRG_ID =  'ARCHIVE_NRG'
ARCHIVE_CASD_ID =  'ARCHIVE_CASD'
ARCHIVE_CASP_ID =  'ARCHIVE_CASP'
ARCHIVE_PDB_ID =  'ARCHIVE_PDB'

CASD_DB_USER_NAME = 'casdcing1'
CASD_DB_NAME = 'casdcing'

CASP_DB_USER_NAME = 'caspcing1'
CASP_DB_NAME = 'caspcing'

NRG_DB_USER_NAME = 'nrgcing1'
NRG_DB_NAME = 'nrgcing'
NRG_DB_SCHEMA = NRG_DB_NAME

PDB_DB_USER_NAME = 'pdbcing1'
PDB_DB_NAME = 'pdbcing'

PDBJ_DB_USER_NAME = 'pdbj'
PDBJ_DB_NAME = 'pdbmlplus'
PDBJ_DB_HOST = 'localhost'
PDBJ_DB_SCHEMA = PDBJ_DB_USER_NAME

CASD_NMR_BASE_NAME = 'CASD-NMR-CING'
inputDirCASD_NMR = 'file:///Users/jd/%s/data' + CASD_NMR_BASE_NAME

CASP_NMR_BASE_NAME = 'CASP-NMR-CING'
inputDirCASP_NMR = 'file:///Users/jd/%s/data' + CASP_NMR_BASE_NAME

schemaIdList = [ CASD_DB_NAME, PDB_DB_NAME, NRG_DB_NAME, CASP_DB_NAME ]