CASD_NMR_BASE_NAME = 'CASD-NMR-CING'
inputDirCASD_NMR = 'file:///Users/jd/%s/data' + CASD_NMR_BASE_NAME

CASD_DB_USER_NAME = 'casdcing1'
CASD_DB_NAME = 'casdcing'

NRG_DB_USER_NAME = 'nrgcing1'
NRG_DB_NAME = 'nrgcing'

ARCHIVE_NRG_ID =  'ARCHIVE_NRG'
ARCHIVE_CASD_ID =  'ARCHIVE_CASD'
ARCHIVE_PDB_ID =  'ARCHIVE_PDB'
