#!/bin/bash

FRACTALS="./fractals -o"
TOPOSCLIENT="topos"
POOL=""
LOCKTIMEOUT="240"

while getopts "t:p:" opt; do
  case $opt in
    t)
      TOPOSCLIENT=$OPTARG
      ;;
    p)
      POOL=$OPTARG
      ;;
  esac
done

function refreshLock {
  local lockname="$1"
  local exitcode=0
  while [ "$exitcode" == "0" ]; do
    sleep $[ (${LOCKTIMEOUT}/2)+10 ]
    $TOPOS refreshLock $POOL $lockname $LOCKTIMEOUT
    exitcode=$?
  done
}

chmod +x "fractals"
chmod +x "${TOPOSCLIENT}"
TOPOS="/bin/sh ${TOPOSCLIENT}"

while [ true ]; do
  tokeninfo=( $( $TOPOS nextTokenWithLock $POOL $LOCKTIMEOUT ) )
  exitCode="$?"
  if [ "$exitCode" != "0" ]; then
    echo "Done!"
    exit $exitCode
  fi
  refreshLock ${tokeninfo[1]} &
  fractalParams=$( $TOPOS getToken $POOL ${tokeninfo[0]} )
  fractalOutput=$( mktemp )
  $FRACTALS $fractalOutput $fractalParams
  if [ "$?" != "0" ]; then
    $TOPOS deleteLock $POOL ${tokeninfo[1]}
    echo "Wrong!"
    continue
  fi
  $TOPOS deleteToken $POOL ${tokeninfo[0]}
  echo $fractalOutput
done
