#@PydevCodeAnalysisIgnore
# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nmv', [dirname(__file__)])
        except ImportError:
            import _nmv
            return _nmv
        if fp is not None:
            try:
                _mod = imp.load_module('_nmv', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _nmv = swig_import_helper()
    del swig_import_helper
else:
    import _nmv
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def initialize_matrix():
  return _nmv.initialize_matrix()
initialize_matrix = _nmv.initialize_matrix

def clear_matrix():
  return _nmv.clear_matrix()
clear_matrix = _nmv.clear_matrix

def free_memory():
  return _nmv.free_memory()
free_memory = _nmv.free_memory

def xplor_read(*args):
  return _nmv.xplor_read(*args)
xplor_read = _nmv.xplor_read

def uncertainty(*args):
  return _nmv.uncertainty(*args)
uncertainty = _nmv.uncertainty

def atom_uncertainty(*args):
  return _nmv.atom_uncertainty(*args)
atom_uncertainty = _nmv.atom_uncertainty

def total_uncertainty():
  return _nmv.total_uncertainty()
total_uncertainty = _nmv.total_uncertainty

def lower_bound(*args):
  return _nmv.lower_bound(*args)
lower_bound = _nmv.lower_bound

def upper_bound(*args):
  return _nmv.upper_bound(*args)
upper_bound = _nmv.upper_bound

cvar = _nmv.cvar

